title: minima
author: Alyson Love
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Rad new stories. Hear all the details straight from the source. 
  The life of Alyson. 365 days a year, updates 24/7. 
 

# social links
instagram_username: alyklove
github_username:  alyklove

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
