---
title: "First Post"
date: 2018-11-24
---
title: Alyson's Blog
author: Alyson Love
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Totally rad new updates straight from the source. Never miss a beat  
  when subscribing to Alyson's blog. Get it here ladies and gents. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
---
